### PR TITLE
436 Knowledge Center Schema

### LINKED ISSUE #436: [Schemas] Cross Sell || Topics || Webinar
Add schema definitions for Cross-sell, Topics(Knowledge Center) and Webinars.

### PR DESCRIPTION
**Pull request by pardeepgera23**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #436 

Test URLs:
- Before: https://main--danaher-abcam--aemsites.hlx.page/en-us/knowledge-center
https://main--danaher-abcam--aemsites.hlx.page/en-us/knowledge-center/cell-biology/exosomes
- After: https://436-knowledge-center-schema--danaher-abcam--aemsites.hlx.page/en-us/knowledge-center
https://436-knowledge-center-schema--danaher-abcam--aemsites.hlx.page/en-us/knowledge-center/cell-biology/exosomes

### CODE REVIEW

**Comment by davenichols-DHLS** [comment]
Hi @pardeepgera23 , thank you for this, but sorry, if I validate the schemas then I can't see any of them?

https://validator.schema.org/#url=https%3A%2F%2F436-knowledge-center-schema--danaher-abcam--aemsites.hlx.page%2Fen-us%2Fknowledge-center%2Fcell-biology%2Fexosomes

**Comment by pardeepgera23** [comment]
> Hi @pardeepgera23 , thank you for this, but sorry, if I validate the schemas then I see them on the hub, but on the details pages I can't see any of them?
> 
> https://validator.schema.org/#url=https%3A%2F%2F436-knowledge-center-schema--danaher-abcam--aemsites.hlx.page%2Fen-us%2Fknowledge-center%2Fcell-biology%2Fexosomes

Hi @davenichols-DHLS  - i can see the schema being correctly validated on detail pages using the above url given by you.

Screenshot 2024-11-26 at 10 00 34 PM

**Comment by davenichols-DHLS** [comment]
@pardeepgera23  - perfect, thank you.  Spooky, I did not see that originally, but I can now.  Thanks!  I approve and will merge.

**Review by davenichols-DHLS — APPROVED** [review]
LGTM - I checked the schema validator

**Review by rgravitvl — APPROVED** [review]

**Pull request merged**
