### PR TITLE
235 Implemented Header menu

### LINKED ISSUE #235: [Navigation] On the Header, change to temp menu
Hi,

Can we please keep the exsiting menu code ( this will be used for 2.0 ), but implement the temp menu drop down to match abcam.com.  This can just be a hardcoded html file to list out the data.  It will appear on hover.

The drop down menu we built here, but it needs to be merged into the current header/navigation.  The search and everything else will stay the same.

https://fix-header-navigation--danaher-abcam--aemsites.aem.page/en-us

### PR DESCRIPTION
**Pull request by Rajesh-GSPANN**
Fix #235 

Test URLs:
- Before: [https://main--danaher-abcam--aemsites.hlx.page/en-us/stories/podcasts/colliderscope-rose-perry](https://main--danaher-abcam--aemsites.hlx.page/en-us/stories/podcasts/colliderscope-rose-perry)
- After: https://235-header-temp-menu--danaher-abcam--aemsites.hlx.page/en-us/stories/articles/beating-the-reproducibility-crisis-together
- After: https://235-header-temp-menu--danaher-abcam--aemsites.hlx.page/en-us/stories/articles/biophysical-quality

### CODE REVIEW

**Comment by davenichols-DHLS** [comment]
@Rajesh-GSPANN  - looking great, just some quick feedback from me:

1 - On the class "bg-white rounded-2xl px-2 py-1", can you add text small, so "bg-white text-sm rounded-2xl px-2 py-1" so that the button text is smaller

2 - On the Header titles, can we change from bold to semi bold, so "pt-2 mb-1 font-bold leading-none menu-item pb-[0.4375rem] w-max border-b-4 border-black hover:border-b-4 hover:border-[#ff7223]" changes to "pt-2 mb-1 font-semibold leading-none menu-item pb-[0.4375rem] w-max border-b-4 border-black hover:border-b-4 hover:border-[#ff7223]"

Thank you!

**Comment by rgravitvl** [comment]
@Rajesh-GSPANN , Pop up position is also can move a bit to left. Thanks

**Comment by Rajesh-GSPANN** [comment]
> @Rajesh-GSPANN - looking great, just some quick feedback from me:
> 
> 1 - On the class "bg-white rounded-2xl px-2 py-1", can you add text small, so "bg-white text-sm rounded-2xl px-2 py-1" so that the button text is smaller
> 
> 2 - On the Header titles, can we change from bold to semi bold, so "pt-2 mb-1 font-bold leading-none menu-item pb-[0.4375rem] w-max border-b-4 border-black hover:border-b-4 hover:border-[#ff7223]" changes to "pt-2 mb-1 font-semibold leading-none menu-item pb-[0.4375rem] w-max border-b-4 border-black hover:border-b-4 hover:border-[#ff7223]"
> 
> Thank you!
> 
> FYI @rgravitvl and @pardeepgera23

Hi @davenichols-DHLS ,
Addressed review comments, can you please have a look at it.

**Comment by Rajesh-GSPANN** [comment]
> @Rajesh-GSPANN , Pop up position is also can move a bit to left. Thanks

Hi @rgravitvl ,
I have checked in 1440 it is in coming center. 
image

**Review by davenichols-DHLS — APPROVED** [review]
LGTM on the front end, please let me know if you have any thoughts @rgravitvl  and @pardeepgera23

**Review by pardeepgera23 — APPROVED** [review]

**Comment by davenichols-DHLS** [comment]
@Rajesh-GSPANN  and @pardeepgera23  - I have created a quick Teams call now if you are OK to join, I just wanted to go through the menu, cheers.

**Comment by davenichols-DHLS** [comment]
Hello @Rajesh-GSPANN  - looks fantastic, I am sending this around to test/validate.

**Comment by davenichols-DHLS** [comment]
@Rajesh-GSPANN  - sorry, one other thing, on my screen the links for Products, Resources and Support all look good with the menu in the same place, but if I hover over About us then the menu changes position?

Products, Resources and Support:
image

About us:
image

**Comment by Rajesh-GSPANN** [comment]
Hi @davenichols-DHLS ,
I have adjusted the position can you please have a look and let us know.

CC: @Meenu-GSPANN @pardeepgera23 @rgravitvl @shivangi1422

**Comment by davenichols-DHLS** [comment]
Thank you @Rajesh-GSPANN , I love this!  @rgravitvl  - are you happy if I merge now?

**Pull request merged**
