### PR TITLE
524 image text field

### LINKED ISSUE #524: [Cross-sell] Add an Image Text Field | Recommended Products
Add and image Text field which can add the text below the images in recommended products

### PR DESCRIPTION
**Pull request by shivangi1422**
Added text field for image text description in recommended products for cross-sell pages

Fix #524 

Test URLs:
- Before: https://main--danaher-abcam--aemsites.hlx.live/
- After: https://524-image-text-field--danaher-abcam--aemsites.hlx.page/en-us/products/product-recommendations/alzheimers-disease-tools

### CODE REVIEW

**Review by pardeepgera23 — APPROVED** [review]
LGTM

**Comment by davenichols-DHLS** [comment]
Sorry @shivangi1422 , can I ask for two changes:  
 
1 - Can the View Product be text-sm
2 - Can the whole card be clickable

**Comment by shivangi1422** [comment]
Hi @davenichols-DHLS I have incorporated the below changes in the PR. Please review it.
1 - Can the View Product be text-sm
2 - Can the whole card be clickable

**Review by davenichols-DHLS — APPROVED** [review]
Love it, thank you.  I see it is approved as well, so now merging.

**Pull request merged**
