### PR TITLE
371 - Adding a text field to the Learn more block

### LINKED ISSUE #371: Add a text field to the Learn More block
Explore

### PR DESCRIPTION
**Pull request by Naveen-Ramgiri**
Fix #371 

Test URLs:
- Before: https://main--danaher-abcam--aemsites.hlx.page/en-us/webinars/webinar-two
- After: https://371-newfield-in-learn-more-block--danaher-abcam--aemsites.hlx.page/en-us/webinars/webinar-two

### CODE REVIEW

**Comment by rgravitvl** [comment]
Hi @Naveen-Ramgiri ,, I don't see any changes in branch URL.

**Review by rgravitvl — CHANGES_REQUESTED** [review]
URL is not having any changes

**Comment by Naveen-Ramgiri** [comment]
Hi @rgravitvl 
Please look for the added text "Explore" to the existing "learn-more" block.

Please find the highlighted text in the below screenshot for your reference.

image

**Comment by rgravitvl** [comment]
@shivangi1422 , As discussed in call, please check with Sunny on the same and proceed further. Thanks

**Comment by shivangi1422** [comment]
Hi @rgravitvl closing this PR as these changes are not needed for now as discussed with sunny.

**Pull request closed without merging**
